package net.ims.what.mixin;

import com.mojang.authlib.minecraft.BanDetails;
import net.ims.what.MultiplayerBan;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import org.jetbrains.annotations.Nullable;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Shadow;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

@Mixin(Minecraft.class)
public class MinecraftMixin {
    @Shadow @Nullable public LocalPlayer player;

    @Overwrite
    private BanDetails multiplayerBan() {
        if (!MultiplayerBan.ready) {
            MultiplayerBan.onInitialize();
        }

        return new BanDetails(UUID.randomUUID(), MultiplayerBan.CONFIG.isPermBan() ? null : Instant.now().plus(MultiplayerBan.CONFIG.getTimeBannedInDays(), ChronoUnit.DAYS), "Fake ban generated by MultiplayerBan");
    }
}
